# Generated by Django 4.2.23 on 2025-07-30 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0002_board_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='members',
        ),
        migrations.AddField(
            model_name='board',
            name='allowed_roles',
            field=models.ManyToManyField(blank=True, related_name='boards_allowed_roles', to='auth.group'),
        ),
        migrations.AddField(
            model_name='board',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='boards_allowed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='board',
            name='created_by',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='created_boards', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
